### ISSUE TITLE
httpd/slowcgi FastCGI parameter mismatch

### ISSUE THREAD

**Issue by Athas** [reyk/httpd#32]
It seems to me that httpd sets the FastCGI variables in a way that slowcgi does not expect.  Specifically, httpd will set SCRIPT_NAME and SCRIPT_FILENAME to the document root (typically a directory), whilst slowcgi will take these variables to indicate the CGI script to run.  Now, as a hack, it *is* possible to point `root` at a specific CGI script in the httpd configuration file, but if you want to run e.g. all `.sh` files with slowcgi, you are in trouble.  For example, this configuration should work:

```
server "default" {
  listen on eggsml.dk port 4242
  root "/htdocs/eggsml.dk"

  location "*.sh" {
    fastcgi socket "/run/eggsmlcgi.sock"
    root "/cgiroot"
  }
}
```

With httpd running in a chroot in /var/www, and requesting `eggsml.dk:4242/index.sh`, this will set both SCRIPT_NAME and SCRIPT_FILENAME to /var/www/htdocs/eggsml.dk, which slowcgi will try to execute (and fail).  Note that slowcgi is *not* running in a chroot (or at least not in /var/www) - it is in essence used to punch a hole in the httpd chroot.  If I do not have the `root` stansa in the `location` field, SCRIPT_NAME and SCRIPT_FILENAME will be set more sensibly to `/htdocs/eggsml.dk/index.sh`, that is, it will include the requested URL.

**Comment by fobser** [comment]
The problem is https://github.com/reyk/httpd/blob/master/httpd/server_fcgi.c#L211
but I don't grok (yet) what that PATH_INFO code is supposed to do.

**Comment by nopjmp** [comment]
The variables should be set to the following:
SCRIPT_NAME: `/index.sh`
SCRIPT_FILENAME `/htdocs/eggsml.dk/index.sh`
PATH_INFO: ` ` (nothing)

PATH_INFO is for when you do something like /index.sh/foo/bar. You have to be careful with PHP as PHP will attempt to 'fix' the path_info variable due to old bugs in Apache.

**Comment by reyk** [comment]
There still seem to be issues with PATH_INFO that have to be addressed.

To get the history: the current implementation is based on previous feedback that it should behave this way. Maybe this way wrong.

**Comment by Athas** [comment]
I worry there is no way that works in general.  All other `slowcgi` setups I can find (for other servers) fiddle with the FastCGI knobs, which is not permitted in the `httpd` configuration language.

I don't know for which use cases the current defaults work, but they do not permit a full replacement of classic CGI using `slowcgi`.

**Comment by hrkfdn** [comment]
I've noticed (maybe related?) problems with uWSGI (in FastCGI mode) and Python applications as reported in https://github.com/reyk/httpd/pull/38

**Comment by reyk** [comment]
After checking this again:

It is neither supported nor encouraged to run slowcgi outside of the chroot. And you should never run shell scripts from a web server without chroot. Don't run any web apps without chroot. Until you want to have another #shellshock ...

To run shell scripts with httpd and slowcgi the described way, you would have to do the following:

    # mkdir -p /var/www/bin/ /var/www/cgiroot/
    # cp /bin/sh /var/www/bin/
    # cp test.sh /var/www/cgiroot/

Eventually add /var/www/dev, etc/resolv.conf if needed. /bin/sh is already statically linked but other tools could need libc or static linking.

Configure httpd accordlingly:

        location "*.sh*" {
                fastcgi
                root "/cgiroot"
        }

Please note that it is matching "*.sh*" instead of "*.sh" to match anything after the script name for PATH_INFO. If you want to turn off PATH_INFO, remove the trailing *.

Now run httpd and slowcgi (with the defaults):

    # httpd
    # slowcgi

Or

    # rcctl enable httpd
    # rcctl enable slowcgi

You can also run slowcgi with an alternate chroot as long as the layout is the same, eg.

    # mkdir -p /var/slowcgi/bin/ /var/slowcgi/cgiroot/
    # cp /bin/sh /var/slowcgi/bin/
    # cp test.sh /var/slowcgi/cgiroot/
    # slowcgi -p /var/slowcgi

I have a test.sh script with the following contents:

    #!/bin/sh
    echo -n "Content-Type: text/plain\r\n\r\n"
    echo "SCRIPT_NAME: $SCRIPT_NAME"
    echo "SCRIPT_FILENAME: $SCRIPT_FILENAME"
    echo "PATH_INFO: $PATH_INFO"
    exit 0

And get the following results for http://127.0.0.1/test.sh/foobar

    SCRIPT_NAME: /test.sh
    SCRIPT_FILENAME: /cgiroot/test.sh
    PATH_INFO: /foobar

And for http://127.0.0.1/test.sh:

    SCRIPT_NAME: /test.sh
    SCRIPT_FILENAME: /cgiroot/test.sh
    PATH_INFO: 

Where PATH_INFO is empty.

Reyk

**Comment by nopjmp** [comment]
The reason the script works is because SH interprets a missing variable $PATH_INFO as empty. Some FastCGI programs expect PATH_INFO to be set to empty and #38 fixes this for me with UWSGI where the the PATH_INFO being missing. As stated by #38 the RFC requires the PATH_INFO variable to be explicit set to empty.
