### ISSUE TITLE
Downloading large files hogs the memory

### ISSUE THREAD

**Issue by hrkfdn** [reyk/httpd#47]
Hey,

I have a VPS with 1G of RAM and 2GB of swap running OpenBSD 5.7 stable and httpd compiled from CURRENT.

When I download a file of 1.8G size, httpd slowly takes up all the main memory and later on the swap is utilized, at which point the transfer slowly starts to stall. Eventually the system becomes unresponsive to the point where only a reboot helps. This is reproducible.

I'm assuming httpd streams the file in some way, but maybe the buffering is too aggressive?

-- Henrik

**Comment by hrkfdn** [comment]
Fixed with this commit: http://marc.info/?l=openbsd-cvs&m=143706418503519&w=2

**Comment by AceJase** [comment]
Hi @reyk, apologies for dragging up an old closed issue, however I am having this exact same issue on 6.5-current - my 1G VPS exhausts in mem/disk and then crashes then OS when I request a file from Nextcloud that is larger than the available mem+swap.

This has been an issue for me since 6.3 (the version I deployed on just over a year ago) - it's taken me this long to find it as it's only an occasional inconvenience. Swapping out httpd for nginx was the test that ultimately told me that httpd was the culprit, and further googling suggests that httpd does attempt to buffer the entire file from a cgi source (php-fpm in this case) rather than chunking it if there isn't sufficient memory.

Is it possible the documented fix above was reverted/regressed? Or is this behaviour by design?
